num_1 = float(input('Введите первое чило '))
num_2 = float(input('Введите второе число '))
num_1 = round(num_1)
num_2 = round(num_2)
print(num_1)
print(num_2)
print(num_1 + num_2)
print(num_1 - num_2)
print(num_1 * num_2)
print(num_1 / num_2)
print(num_1 // num_2)
print(num_1 % num_2)
print(num_1 ** num_2)
