first_name = (input('Введите ваше имя: '))
last_name = (input('Введите вашу фамилию: '))
print('Привет!!:', first_name, last_name, sep=' ')
print('----------------------')
itea_day = int(19)
itea_month = int(11)
itea_year = int(2018)
my_day = int(input('Введите день своего рождения:  '))
my_month = int(input('Введите месяц своего рождения:  '))
my_year = int(input('Введите год своего рождения:  '))
my_month = (my_year * 12 + my_month)
my_day = (my_month * 30 + my_day)
itea_month = (itea_year * 12 + itea_month)
itea_day = (itea_month * 30 + itea_day)
itea_date = int((2018 * 360) + (11 * 30) + 19)
result_year = int((itea_date - my_day) / 360)
result_month = int((itea_date - my_day) / 30)
result_day = int(itea_date - my_day)
print('----------------------')
print('Количесво прожитых лет до начала курса:  ', result_year)
print('Количесво прожитых месяцев до начала курса:  ', result_month)
print('Количесво прожитых дней до начала курса:  ', result_day)